apiVersion: v1
kind: Service
metadata:
  name: blocky-ui
  namespace: blocky
  labels:
    app: blocky-ui
spec:
  type: ClusterIP
  selector:
    app: blocky-ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
